// Canonical wind-policy dimension taxonomy (feature spec §4) = the comparison ROWS.
// Keys are an API contract: extend, never rename. sort_order increments by 10
// within a category; category render order is CATEGORY_ORDER in types.ts.

import type { DimensionDef } from "./types";

export const DIMENSIONS: DimensionDef[] = [
  // ── pricing ───────────────────────────────────────────────────────────────
  {
    key: "preferential_tariff",
    label: "Preferential / feed-in tariff",
    category: "pricing",
    value_type: "numeric",
    unit: "₹/kWh",
    enum_values: null,
    description:
      "State preferential / feed-in tariff for wind. Many states have moved off a fixed FIT to competitive bidding or APPC — where so, this is silent and tariff_mode carries the method.",
    sort_order: 10,
  },
  {
    key: "tariff_mode",
    label: "Tariff determination",
    category: "pricing",
    value_type: "enum",
    unit: null,
    enum_values: ["APPC", "preferential", "competitive_bidding", "project_specific"],
    description:
      "How the procurement tariff is set: APPC (average power purchase cost), a preferential/feed-in tariff, competitive bidding, or project-specific determination.",
    sort_order: 20,
  },
  // ── open_access ─────────────────────────────────────────────────────────────
  {
    key: "third_party_sale",
    label: "Third-party sale allowed",
    category: "open_access",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether wind generators may sell power to third parties via open access.",
    sort_order: 10,
  },
  {
    key: "captive_use",
    label: "Captive use allowed",
    category: "open_access",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether wind projects may be set up for captive consumption.",
    sort_order: 20,
  },
  {
    key: "geoa_threshold_kw",
    label: "Green OA min load",
    category: "open_access",
    value_type: "numeric",
    unit: "kW",
    enum_values: null,
    description:
      "Minimum contracted demand / connected load to qualify for Green Energy Open Access (GEOA Rules 2022 set the national floor at 100 kW).",
    sort_order: 30,
  },
  // ── charges ─────────────────────────────────────────────────────────────────
  {
    key: "wheeling_charge",
    label: "Wheeling charge",
    category: "charges",
    value_type: "numeric",
    unit: "₹/kWh",
    enum_values: null,
    description:
      "Charge for using the distribution network to wheel wind power. Often expressed as a rule (e.g. a % of the conventional charge) rather than a fixed ₹/kWh.",
    sort_order: 10,
  },
  {
    key: "wheeling_concession",
    label: "Wheeling concession for wind",
    category: "charges",
    value_type: "numeric",
    unit: "%",
    enum_values: null,
    description: "Concession on wheeling/transmission charges granted specifically to wind.",
    sort_order: 20,
  },
  {
    key: "css_applicable",
    label: "Cross-subsidy surcharge applies",
    category: "charges",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether cross-subsidy surcharge (CSS) applies to wind open-access consumers.",
    sort_order: 30,
  },
  {
    key: "css_concession",
    label: "CSS concession for wind",
    category: "charges",
    value_type: "numeric",
    unit: "%",
    enum_values: null,
    description:
      "Concession on cross-subsidy surcharge for wind. GEOA Rules 2022 cap CSS escalation at +50% of the first-year value over the first 12 years.",
    sort_order: 40,
  },
  {
    key: "additional_surcharge",
    label: "Additional surcharge applies",
    category: "charges",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether an additional surcharge applies to wind open-access consumers.",
    sort_order: 50,
  },
  {
    key: "transmission_loss",
    label: "Transmission/wheeling losses",
    category: "charges",
    value_type: "numeric",
    unit: "%",
    enum_values: null,
    description:
      "Applicable transmission/wheeling losses. Some states levy actual line losses in kind rather than a fixed statutory %.",
    sort_order: 60,
  },
  // ── banking ─────────────────────────────────────────────────────────────────
  {
    key: "banking_allowed",
    label: "Banking allowed",
    category: "banking",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether banking of wind energy with the grid is permitted.",
    sort_order: 10,
  },
  {
    key: "banking_period",
    label: "Banking settlement period",
    category: "banking",
    value_type: "enum",
    unit: null,
    enum_values: ["none", "monthly", "annual", "seasonal"],
    description: "The cycle over which banked energy is settled before unused units lapse.",
    sort_order: 20,
  },
  {
    key: "banking_charge",
    label: "Banking charge",
    category: "banking",
    value_type: "numeric",
    unit: "%",
    enum_values: null,
    description: "Charge levied on banked energy (often a % drawn in kind).",
    sort_order: 30,
  },
  {
    key: "banking_third_party",
    label: "Banking for third-party OA",
    category: "banking",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether banking is available to third-party open-access (not just captive) consumers.",
    sort_order: 40,
  },
  // ── rpo ─────────────────────────────────────────────────────────────────────
  {
    key: "rpo_wind",
    label: "Wind-specific RPO",
    category: "rpo",
    value_type: "numeric",
    unit: "%",
    enum_values: null,
    description:
      "Wind-specific Renewable Purchase Obligation (now termed Renewable Consumption Obligation / RCO at the national level under the MoP notification).",
    sort_order: 10,
  },
  {
    key: "rpo_total",
    label: "Total RPO",
    category: "rpo",
    value_type: "numeric",
    unit: "%",
    enum_values: null,
    description: "Total Renewable Purchase / Consumption Obligation across all RE sources.",
    sort_order: 20,
  },
  // ── dispatch ────────────────────────────────────────────────────────────────
  {
    key: "must_run",
    label: "Must-run status",
    category: "dispatch",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether wind enjoys must-run status (limited curtailment).",
    sort_order: 10,
  },
  // ── repowering ──────────────────────────────────────────────────────────────
  {
    key: "repowering_incentive",
    label: "State repowering incentive",
    category: "repowering",
    value_type: "text",
    unit: null,
    enum_values: null,
    description:
      "State-level repowering / life-extension incentives, over and above the National Repowering & Life Extension Policy 2023.",
    sort_order: 10,
  },
  // ── land ────────────────────────────────────────────────────────────────────
  {
    key: "land_allotment",
    label: "Land allotment process",
    category: "land",
    value_type: "text",
    unit: null,
    enum_values: null,
    description: "How government/private land is allotted for wind projects.",
    sort_order: 10,
  },
  {
    key: "gram_panchayat_noc",
    label: "Gram Panchayat NOC required",
    category: "land",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether a Gram Panchayat no-objection certificate is required.",
    sort_order: 20,
  },
  // ── incentives ──────────────────────────────────────────────────────────────
  {
    key: "electricity_duty_exemption",
    label: "Electricity duty exemption",
    category: "incentives",
    value_type: "text",
    unit: null,
    enum_values: null,
    description: "Any exemption from electricity duty for wind generation/consumption.",
    sort_order: 10,
  },
  {
    key: "green_energy_cess",
    label: "Green energy cess",
    category: "incentives",
    value_type: "numeric",
    unit: "₹/kWh",
    enum_values: null,
    description: "Any green-energy cess / development fund levy on wind.",
    sort_order: 20,
  },
  // ── clearances ──────────────────────────────────────────────────────────────
  {
    key: "single_window",
    label: "Single-window clearance",
    category: "clearances",
    value_type: "boolean",
    unit: null,
    enum_values: null,
    description: "Whether the state offers single-window clearance for wind projects.",
    sort_order: 10,
  },
];
