import { Router, Request, Response } from 'express';
import { requirePro } from '../middleware/requirePro';
import fs from 'fs';
import path, { dirname } from 'path';
import { fileURLToPath } from 'url';

const router = Router();

const __dirname = dirname(fileURLToPath(import.meta.url));
// src/routes → src → apps/api, then into data/private.
const GEOJSON_PATH = path.resolve(
  __dirname,
  '../../data/private/boundaries.geojson',
);

// Parse + cache once. The file is generated by scripts/ingest-boundaries.ts
// from the proprietary boundaries.kmz and never changes at runtime.
let cache: string | null = null;

function loadBoundaries(): string | null {
  if (cache) return cache;
  try {
    cache = fs.readFileSync(GEOJSON_PATH, 'utf-8');
    return cache;
  } catch (err) {
    console.error('[boundaries] could not read boundaries.geojson', err);
    return null;
  }
}

// GET /api/boundaries — proprietary wind-farm site boundaries (Pro-only).
// Served as a single GeoJSON FeatureCollection the Pro map renders as a layer.
router.get('/boundaries', ...requirePro, (_req: Request, res: Response) => {
  const data = loadBoundaries();
  if (!data) {
    res.status(503).json({ error: 'Boundaries unavailable' });
    return;
  }
  res.setHeader('Content-Type', 'application/json');
  res.setHeader(
    'Cache-Control',
    process.env.NODE_ENV === 'production' ? 'private, max-age=3600' : 'no-store',
  );
  res.send(data);
});

export default router;
